"""
Report schemas for Atlas synthesis and drafting.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class ReportSection(BaseModel):
    """A single coherent section of the research report."""
    
    heading: str = Field(description="Section title / heading")
    sub_question_id: Optional[str] = Field(default=None, description="The sub-question this section corresponds to")
    content: str = Field(description="Section body in markdown format with [E#] inline citations")
    cited_evidence_ids: List[str] = Field(default_factory=list, description="List of evidence IDs cited in this section")


class DraftReport(BaseModel):
    """The structured draft generated by the Writer Agent."""
    
    title: str = Field(description="Comprehensive report title")
    executive_summary: str = Field(description="High-level synthesis and key findings with [E#] citations")
    sections: List[ReportSection] = Field(default_factory=list, description="Detailed thematic sections")
    key_takeaways: List[str] = Field(default_factory=list, description="Bullet points of major strategic conclusions")
    raw_markdown: str = Field(default="", description="Full compiled markdown document")
    iteration: int = Field(default=1, description="Draft iteration number")

    def compile_markdown(self, bibliography_markdown: str = "") -> str:
        """Compile the complete report into GitHub-flavored Markdown."""
        parts = [
            f"# {self.title}\n",
            "## Executive Summary\n",
            f"{self.executive_summary}\n",
        ]
        
        for sec in self.sections:
            parts.append(f"## {sec.heading}\n")
            parts.append(f"{sec.content}\n")
            
        if self.key_takeaways:
            parts.append("## Strategic Key Takeaways\n")
            for t in self.key_takeaways:
                parts.append(f"- {t}")
            parts.append("\n")
            
        if bibliography_markdown:
            parts.append(bibliography_markdown)
            
        self.raw_markdown = "\n".join(parts)
        return self.raw_markdown
